language: php
php:
- '7.1'
env:
  global:
  - ZIP_FILENAME=bmlt-drupal-build${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
  - S3_BUCKET=archives.bmlt.app
  - S3_KEY=bmlt-drupal
jobs:
  include:
  - stage: zip file
    env:
    - BUILD_DIR=build
    - DIST_DIR_S3=dist/s3
    - DIST_DIR_GITHUB=dist/github
    - GITHUB_RELEASE_FILENAME=bmlt-drupal7.zip
    install:
    - composer install --no-dev
    script:
    - find ./ -type d | xargs chmod 755
    - find ./ -name '*.php' | xargs chmod 644
    - zip -r $ZIP_FILENAME ./ -x "*.git*" -x "*.editorconfig*" -x "*.travis.yml*" -x "*doc*" -x "composer.*" && mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
    before_deploy:
    - mkdir -p $DIST_DIR_S3 && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_S3/$ZIP_FILENAME
    - mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
    deploy:
    - provider: s3
      access_key_id: AKIAI7JHYFA6DI3WYP5A
      secret_access_key:
        secure: KZwepitktfvcLgOFf3MLHPwrzdXPPqLEPujeH5hRT8vyTwt2hb1rMHhziGJITlaFm6hE6fSD84NZJyOourKCeYxAKZ+VnqKfUxGhgz8OYWO/xJcociVqew1i/UWi6gnPNdy3RwAlxnuZnQSAy4/NNx68l0dR6jABlLrGnD+l9x70rb/Z1XJijC5NDM3P92ROqhFZlfJXLb41OUhFK1zJIOXYhyOZn/0Fq6KU3+XPfDclT+ltRORncUjY5HsWrFKqWYkhtRoFI9qBqNULNGerO1dNQl/ESWbPprcPLegwjQmqq6T3FOxB6G5rFVgp+uDHzrfikq5YsdX9pzZKu02916mn+c/4uxeZLAoKSwZ9vSvI1fzVS3qiDi/JlbZFBno0cIMLhNtODl8LvWtMyPpZove2fMcwxYNl9usobndX1OppItmB0FbGaZZmE1sJVciupwuoa1k9E6PdwFSFtorIWI+P26IlGiBc11QtsZtIZfvFA383nwHia9runcXuLtFQZVOb1+VULuj2ELk6oewIAiyX0ab1XWdETu5OXYiGbZv++aNkEQ2PgBE+1rC5bUjw+5C05rYmqy1hsGr5KZ7tj+zK0OJNVfi8L65OUwd4KraReiSqB6ae728jSLx76v0Cxd6yZTHXSzQJvWPUgWhardwBx9Zy34efhtlprUJwaRU=
      bucket: "$S3_BUCKET"
      local_dir: "$DIST_DIR_S3"
      upload-dir: "$S3_KEY"
      skip_cleanup: true
      on:
        all_branches: true
    - provider: releases
      api_key:
        secure: HwYdxLMnfREm3LHytbTswgsT61UKI0HpakWkp3JE0owGjA4usVbqYnUOsycplDSvC8kzWOXXJkvimDh6MHhjtVgCteZ5tTIioQrWJo/0X8NXx32UScTMF5tXZHQX9KS201UeopfZvlyMXoOdcm+m7/iGTYrfVwbWnVnjpDGtvJdes09uJUIOCvEUjfUbIpUtlXNpnFc4DuXhkJvIG8XqGu9uQt2k8GtruV1YTR2CRrCaVPzRNBaEAP6lN+pHWy8j9af9PzxWZ9GrGTh/Cwuegp2tuq6gZPSWfqEdN/JzHmlRwy8+4JchYWUNKLZsT6x4QH8h1Kzi/vHveIxtzOvFXa/oTZKBGVqhJk1FdZ9rgIUsFPWS4OPQv3pCbng3LJhazHjEgi9EPk9aIcIZzPIKAGCooHdHLfnNJt3NT+xGz6nkoEXHqAuvCsEQLq9RUEQ+XNP7iK/D8QpJ7A2sBAx7M6H8sImnxMHVPZF/RGATjhzbgnn6WgOOsEi6rsrquBDDL3A8BhXKCtsBcF6jVwKWUDfsi2ZRnmmmDJmbwNPztwrtG18RbWy+UO9sHxO9UXPgjRXwbR5B44iT58wvJKxVgt8uFfSlIdWqFtRSNDePjd15IFGVASWbMRS7abA7ZnrZErmxswpO5Eg0IwygQ4wWpxdrf1eRTXXY8s1EGx8wU1A=
      file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
      skip_cleanup: true
      name: "$TRAVIS_TAG"
      on:
        tags: true
notifications:
  slack:
    rooms:
    - secure: bmoIugz9sorNakDw7LnfC3iB7a4CnhuZeZBAVxefSoqipbZAGLoA86pSaDwSK3kNsCRAUXyHJ0pBxxJuCO5jrQKhl9TNBFQQ60KPvn3LQj9OXXTSHp4qoqBytipQGyjeqySu4fJt8Lc0u8FQ0qinxn21qF7K7c54aygVKQd+nxf/+9rVzSOJIY+c6UEBb9FwKfHl9cOJy8nTHYPNl0ZbQaYVS1gvyOV2jzrlurOXb0t2xYs2W9EOAjUd2E4ZVaD8EEyRZ9zcvy8ne41qZGBLMJjHZo6TdN4x0AdEYiITst5fKj+YILNCaVQMyURu5h65RPVXyjZ/eIOUixSt1EOpMTxWcRiDn3H7B2F7eEUIXyo/c5x1AEWEQFLGK+/PEqWx/zaBG0rJJdzVbLaqet2kg5piy+f84EBCZiXm7CZIYPMSjLJo9AJDcY9iSRgvpRnkSagHZAgMILNut53aNPd8i3FoOeycPwux/KDQpSz0uIpn4xu26VY0bzxJ8N27VugUhmNhLCN05Hgw8GoDjEoh4EgPPsdNVzXT4mzpjx2GfhRZOm/78LUSDB/w3oIAEPzRFfhberBAo0l2w9T5+Ynbw9yyquYgNUOW/nMhbwqOPbWqndHa8Xume0DXp2COHEqoSZx4gDIIRRKjKdsrFjjasWB5K7IQXQfBoiGAL7EscNA=
    on_success: change
  email: false
