<?php
/**
	\file bmlt/bmlt.module
	\brief The implementation of the Drupal BMLT satellite server module.
	\version 2.1.8
	//$Id$
    
    This file is part of the Basic Meeting List Toolbox (BMLT).
    
    Find out more at: http://magshare.org/bmlt
    
    BMLT is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    
    BMLT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    
    You should have received a copy of the GNU General Public License
    along with this code.  If not, see <http://www.gnu.org/licenses/>.
*/
require_once ( dirname ( __FILE__ ).'/bmlt-drupal-satellite-plugin.php' );

/***********************************************/
/**
	\brief Sets up the menu for the BMLT
*/
function bmlt_menu ( ) 
	{
    global $BMLTPluginOp;
    
    $items = array('admin/settings/bmlt' => array (
                            'title' => $BMLTPluginOp->process_text( $BMLTPluginOp->local_strings['en']['bmlt_settings'] ),
                            'description' => $BMLTPluginOp->process_text( $BMLTPluginOp->local_strings['en']['describe_admin'] ),
                            'page callback' => 'bmlt_admin_form',
                            'access arguments' => array ( $BMLTPluginOp->process_text ( $BMLTPluginOp->local_strings['en']['access_admin'] ) )
                            )
                        );
	return $items;
	}

/***********************************************/
/**
	\brief This function returns the HTML for the BMLT admin.
*/
function bmlt_admin_form ( )
	{
    global $BMLTPluginOp;
    $BMLTPluginOp->admin_head();
    return $BMLTPluginOp->return_admin_page();
	}

/***********************************************/
/**
	\brief This function sets up the header for the module.
*/
function bmlt_boot ( )
	{
    global $BMLTPluginOp;

    if ( $BMLTPluginOp->my_http_vars['q'] == 'admin' )
        {
        $BMLTPluginOp->admin_ajax_handler();
        }
    else
        {
        $BMLTPluginOp->ajax_router();
        }
	}

/***********************************************/
/**
	\brief	This displays the actual BMLT content if the
			text has "<!--BMLT-->" in it.
*/
function bmlt_filter (	$op = 'list',
						$delta = 0,
						$format = -1,
						$text = '',
						$cache_id = 0
						)
    {
    }

/***********************************************/
/**
	\brief	This displays the actual BMLT content.
*/
function bmlt_block (	$op = 'list',
						$delta = 0,
						$edit = array(),
						$is_filter = false
					)
	{
	}
